-- Création de la structure complète conforme à cookasian.sql

CREATE TABLE users (
  id INT UNSIGNED NOT NULL,
  email VARCHAR(190) NOT NULL,
  name VARCHAR(100) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  remember_token VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE recettes (
  id INT UNSIGNED NOT NULL,
  titre VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  temps_preparation INT UNSIGNED NOT NULL,
  temps_cuisson INT UNSIGNED NOT NULL,
  difficulte ENUM('facile','moyen','difficile') NOT NULL DEFAULT 'moyen',
  nombre_personnes TINYINT UNSIGNED NOT NULL DEFAULT 4,
  image_url VARCHAR(500) NOT NULL,
  pays_origine VARCHAR(100) NOT NULL,
  date_creation TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  date_modification TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ingredients (
  id INT UNSIGNED NOT NULL,
  recette_id INT UNSIGNED NOT NULL,
  nom VARCHAR(255) NOT NULL,
  quantite VARCHAR(100) NOT NULL,
  ordre TINYINT UNSIGNED NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE etapes (
  id INT UNSIGNED NOT NULL,
  recette_id INT UNSIGNED NOT NULL,
  numero TINYINT UNSIGNED NOT NULL,
  description TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE favoris (
  id INT UNSIGNED NOT NULL,
  utilisateur_id INT UNSIGNED NOT NULL,
  recette_id INT UNSIGNED NOT NULL,
  date_creation DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE contact_messages (
  id INT UNSIGNED NOT NULL,
  nom VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  date_envoi TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
