-- Ajout des AUTO_INCREMENT

ALTER TABLE users MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE recettes MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE ingredients MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE etapes MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE favoris MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE contact_messages MODIFY id INT UNSIGNED NOT NULL AUTO_INCREMENT;
